import { useRouter } from "next/router";
import Head from "next/head";
import { ArrowLeftIcon } from "@heroicons/react/outline";
import {
  collection,
  doc,
  onSnapshot,
  orderBy,
  query,
} from "firebase/firestore";
import { useEffect, useState } from "react";

import { CommentModal, Sidebar, Widgets } from "../../containers";
import { Comment, Post } from "../../components";
import { db } from "../../firebase";

const PostPage = ({ newsResults, randomUsers }) => {
  const router = useRouter();
  const { id } = router.query;
  const [post, setPost] = useState(null);
  const [comments, setComments] = useState([]);

  // get post data
  useEffect(
    () => onSnapshot(doc(db, "posts", id), (snapshot) => setPost(snapshot)),
    [id]
  );

  // get post comments
  useEffect(() => {
    onSnapshot(
      query(
        collection(db, "posts", id, "comments"),
        orderBy("timestamp", "desc")
      ),
      (snapshot) => setComments(snapshot.docs)
    );
  }, [id]);

  return (
    <div>
      <Head>
        <title>Post</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen mx-auto">
        {/* Sidebar */}
        <Sidebar />

        <div className="xl:ml-[370px] border-l border-r border-gray-200 xl:min-w-[576px] sm:ml-[73px] flex-grow max-w-xl ">
          {/* Header */}
          <div className="flex items-center space-x-2 py-2 px-3 sticky top-0 z-50 bg-white border-b border-gray-200">
            <div
              className="hover-effect flex items-center justify-center"
              onClick={() => router.push("/")}
            >
              <ArrowLeftIcon className="h-5" />
            </div>
            <h2 className="text-lg sm:text-xl font-bold cursor-pointer">
              Tweet
            </h2>
          </div>

          <Post id={id} post={post} />

          {/* Comments */}
          {comments.length > 0 ? (
            <>
              <div className="">
                {comments.map((comment) => (
                  <Comment
                    key={comment.id}
                    commentId={comment.id}
                    commentPostId={id}
                    comment={comment?.data()}
                  />
                ))}
              </div>
            </>
          ) : (
            <p>No comments yet</p>
          )}
        </div>

        {/* Widgets */}
        <Widgets
          newsResults={newsResults.articles}
          randomUsers={randomUsers.results}
        />

        {/* Modal */}
        <CommentModal />
      </main>
    </div>
  );
};
export default PostPage;

export async function getServerSideProps() {
  const newsResults = await fetch(
    "https://saurav.tech/NewsAPI/everything/cnn.json"
  ).then((res) => res.json());

  // Who to follow

  const randomUsers = await fetch(
    "https://randomuser.me/api/?results=30&inc=name,login,picture"
  ).then((res) => res.json());

  return {
    props: { newsResults, randomUsers },
  };
}
