import Head from "next/head";
import { Feed, Sidebar, Widgets } from "../containers";

export default function Home({ newsResults, randomUsers }) {
  return (
    <div>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen mx-auto">
        {/* Sidebar */}
        <Sidebar />

        {/* Feeds */}
        <Feed />

        {/* Widgets */}
        <Widgets newsResults={newsResults.articles} randomUsers={randomUsers.results} />

        {/* Modal */}
      </main>
    </div>
  );
}

// https://saurav.tech/NewsAPI/everything/cnn.json

export async function getServerSideProps() {
  const newsResults = await fetch(
    "https://saurav.tech/NewsAPI/everything/cnn.json"
  ).then((res) => res.json());

  // Who to follow

  const randomUsers = await fetch(
    "https://randomuser.me/api/?results=30&inc=name,login,picture"
  ).then((res) => res.json());

  return {
    props: { newsResults, randomUsers },
  };
}
